   7 function: CheckFormComplete
   6 procedure: spFibroidCountOnChange
   6 procedure: cbToggleCheckOnClick
   6 procedure: cbFibroidsVisualisedOnClick
   6 procedure: StartScript
   6 procedure: ProduceMergeFieldData
   6 procedure: InitializeScreen
   6 function: StringReplace
   6 function: StrToIntDef
   6 function: StrToFloatDef
   6 function: Max
   6 function: InitCaps
   6 function: IncludeComma
   6 function: GetSingleFibroidDimensions
   6 function: GetSingleFibroid
   6 function: GetNumberString
   6 function: GetIntegerMeasuredString
   6 function: GetIndefinateArticle
   6 function: GetFullDateString
   6 function: GetCavDistortionCount
   6 function: AddToResult
   6 function: AddFullstopToEnd
   6 function: AddFullStop
   
   5 procedure: deStatedEDDOnChange
   5 procedure: PopulateEDDControls
   5 function: getFibroid
   5 function: StringReplaceAll
   5 function: PadDecimalPlaces
   5 function: Min
   5 function: GetWeeksFromDueDate
   5 function: GetSingleCloseOrClear
   5 function: GetFibroidString
   5 function: GetDaysFromDueDate
   5 function: GetClinicalIndicators
   5 function: GetClinicalHistory
   4 procedure: cxccbReferralIndicatorsChange
   4 procedure: cxccbObstetricHistoryChange
   4 procedure: cbFetalAnatomyNormal1OnClick
   4 procedure: ToggleCloseToCervixFibroid
   4 procedure: SetAbnormalCheckes
   4 procedure: ProduceMergeOrder
   4 function: getPlacentaConclusion
   4 function: getFunnelingMembranes
   4 function: getEFW
   4 function: getCervixConclusion
   4 function: GetValueSuffix
   4 function: GetPerGraph
   4 function: GetObstetricHistory
   4 function: GetLiquor95Centile
   4 function: GetLiquor5Centile
   4 function: GetGraphXValue
   4 function: GetGestWeeks
   4 function: GetGestDays
   3 procedure: getBiometryPercentiles
   3 procedure: cxccbReferralIndicationChange
   3 procedure: cbUSSEDDOnChange
   3 procedure: cbGestationTypeChange
   3 procedure: btnClear1OnClick
   3 procedure: GetGraphData
   3 function: getOvaryWarning
   3 function: getGAFromEnteredEDD
   3 function: getEFWPer
   3 function: getConclusionWarnings
   3 function: getCompositeDate
   3 function: getCervixWarning
   3 function: GetPlacenta1Measure
   3 function: GetPlacenta
   3 function: GetOvary
   3 function: GetNormalUAPIRange
   3 function: GetNormalMCAPIRange
   3 function: GetNormalCPRRange
   3 function: GetMoMRange
   3 function: GetEnteredEDD
   2 procedure: seTransferDayOnChange
   2 procedure: deOvulationEDDOnChange
   2 procedure: deMenstrualEDDOnChange
   2 procedure: deMUFWEddOnChange
   2 procedure: deIVFEDDOnChange
   2 procedure: cbLMPDateOnChange
   2 procedure: cbFibroidsTypeOnChange
   2 procedure: cbEDDPrincipleOnChange
   2 procedure: cbDateOfConceptionOnChange
   2 procedure: btnSelectAll1OnClick
   2 procedure: btnPregnancyRedatedOnClick
   2 procedure: btnGeneratePercentilesOnClick
   2 procedure: btnCalGrowthPer1OnClick
   2 procedure: CalcFetalScore
   2 function: getReportHeading
   2 function: getPresentation
   2 function: getPlacentalPosition
   2 function: getPlacentaBeyond
   2 function: getPlacenta2Position
   2 function: getFunnellingMembrane
   2 function: getCervixDetailed
   2 function: getCervix
   2 function: getCervicalSuture
   2 function: getAnatomyWarning
   2 function: getAnatomyChecked
   2 function: SetAnatomyChecks
   2 function: RemoveDecimalPointAtEnd
   2 function: GetWeeksFromLMPDate
   2 function: GetUAPI
   2 function: GetSingleFibroidCavity
   2 function: GetPlacenta1InvertPosition
   2 function: GetMCAPI
   2 function: GetLeftOvaryCyst
   2 function: GetLargestFibroid
   2 function: GetFrozen
   2 function: GetFibroidDesc
   2 function: GetFibroidCount
   2 function: GetFibroidConcl
   2 function: GetFibroidAvg
   2 function: GetFamilyHistory
   2 function: GetEmbryoTransferCount
   2 function: GetDuctusVenosusWarning
   2 function: GetDaysFromLMPDate
   2 function: GetCycleDaysString
   2 function: GetCavProjectionString
   2 function: GetBioPhysicalConc
   2 function: GetAnatomy
   1 procedure: tcbMedicationChange
   1 procedure: seRightResidualFolCountOnChange
   1 procedure: seRightOvarianCystsCountOnChange
   1 procedure: seRightLeadFollicleOnChange
   1 procedure: seRightFolCountOnChange
   1 procedure: seRightCorpusLuteumOnChange
   1 procedure: seRightAdnexalMassesOnChange
   1 procedure: sePolypCountOnChange
   1 procedure: seLeftResidualFolCountOnChange
   1 procedure: seLeftOvarianCystsCountOnChange
   1 procedure: seLeftLeadFollicleOnChange
   1 procedure: seLeftFolCountOnChange
   1 procedure: seLeftCorpusLuteumOnChange
   1 procedure: seLeftAdnexalMassesOnChange
   1 procedure: seHeartBPM1OnChange
   1 procedure: seEdometriumThicknessOnChange
   1 procedure: edtYolkSacSize1OnChange
   1 procedure: edtMidCerArtPI1Exit
   1 procedure: edtMeanUAPIOnChange
   1 procedure: edtMeanRUAPIOnChange
   1 procedure: edtEmbroSize1OnChange
   1 procedure: edtAFI2Onchange
   1 procedure: edtAFI1Onchange
   1 procedure: edtAFI1Exit
   1 procedure: edNucTransMeasurement1OnExit
   1 procedure: deLMPDateOnChange
   1 procedure: cxpgFetus2Change
   1 procedure: cxccbClinicalHistoryChange
   1 procedure: cxcbGynaeSurgeryChange
   1 procedure: cxcbFamilyHistoryChange
   1 procedure: ccbROInternalContentsChange
   1 procedure: ccbROClassificationOnChnage
   1 procedure: ccbLOInternalContentsChange
   1 procedure: ccbLOClassificationOnChnage
   1 procedure: ccbGestationTypeChange
   1 procedure: cbYolkSacYes1OnClick
   1 procedure: cbYolkSacNo1OnClick
   1 procedure: cbVaultNormalYesOnClick
   1 procedure: cbVaultNormalNoOnClick
   1 procedure: cbVBShadowingPresentOnClick
   1 procedure: cbVBShadowingNotPresentOnClick
   1 procedure: cbUterusTenderClick
   1 procedure: cbUterusNonTenderClick
   1 procedure: cbUterusMobileClick
   1 procedure: cbUterusLimitedMobileClick
   1 procedure: cbUterineShapeOnChange
   1 procedure: cbSuccenturiateLobeYes1OnClick
   1 procedure: cbSuccenturiateLobeNo1OnClick
   1 procedure: cbRightTenderClick
   1 procedure: cbRightReanalAbnormalYesClick
   1 procedure: cbRightOvaryIdentifiedClick
   1 procedure: cbRightOvarianCystClick
   1 procedure: cbRightNonTenderClick
   1 procedure: cbRightMobileClick
   1 procedure: cbRightLimitedMobilityClick
   1 procedure: cbRightLeadFollicleClick
   1 procedure: cbRightKidneyYesClick
   1 procedure: cbRightKidneyNoClick
   1 procedure: cbRightCorpusLuteumClick
   1 procedure: cbRightAdnexalMassClick
   1 procedure: cbRetroFlexedClick
   1 procedure: cbROVSYesOnClick
   1 procedure: cbROSolidYesOnClick
   1 procedure: cbROSolidElementsNoOnClick
   1 procedure: cbROSmoothYesOnClick
   1 procedure: cbROSeptumYesOnClick
   1 procedure: cbROPPYesOnClick
   1 procedure: cbROPPNoOnClick
   1 procedure: cbProceduresPerformedOnClick
   1 procedure: cbPreigHeamYesOnClick
   1 procedure: cbPreigHeamNoOnClick
   1 procedure: cbPostMenopausalOnClick
   1 procedure: cbParousClick
   1 procedure: cbOvaryCystTypeOnChange
   1 procedure: cbNaturalMedicationOnChange
   1 procedure: cbNalliPorousOnClick
   1 procedure: cbMyometrialCystsPresentOnClick
   1 procedure: cbMyometrialCystsNotPresentOnClick
   1 procedure: cbMedicationChange
   1 procedure: cbLeftTenderClick
   1 procedure: cbLeftReanalAbnormalYesClick
   1 procedure: cbLeftOvaryIdentifiedClick
   1 procedure: cbLeftOvarianCystClick
   1 procedure: cbLeftNonTenderClick
   1 procedure: cbLeftMobileClick
   1 procedure: cbLeftLimitedMobilityClick
   1 procedure: cbLeftLeadFollicleClick
   1 procedure: cbLeftKidneyYesClick
   1 procedure: cbLeftKidneyNoClick
   1 procedure: cbLeftCorpusLuteumClick
   1 procedure: cbLeftAdnexalMassClick
   1 procedure: cbLOVSYesOnClick
   1 procedure: cbLOSolidYesOnClick
   1 procedure: cbLOSolidElementsNoOnClick
   1 procedure: cbLOSmoothYesOnClick
   1 procedure: cbLOSeptumYesOnClick
   1 procedure: cbLOPPYesOnClick
   1 procedure: cbLOPPNoOnClick
   1 procedure: cbIrregularCycleClick
   1 procedure: cbIncVasPresentOnClick
   1 procedure: cbIncVasNotPresentOnClick
   1 procedure: cbInCorrectPlacementIUSonClick
   1 procedure: cbInCorrectPlacementIUCDonClick
   1 procedure: cbHysterectomyOnClick
   1 procedure: cbHeartMotionVisYes1OnClick
   1 procedure: cbHeartMotionVisNo1OnClick
   1 procedure: cbHRTYesOnclick
   1 procedure: cbFeatlMovementsClick
   1 procedure: cbFeatlMovements2Click
   1 procedure: cbFeatlMovements1Click
   1 procedure: cbEndometriumChange
   1 procedure: cbEndometrialPolypClick
   1 procedure: cbEmbryo1Visualised1OnClick
   1 procedure: cbEmbryo1NotVisualised1OnClick
   1 procedure: cbEFFNormalClick
   1 procedure: cbEFFAbnormalClick
   1 procedure: cbCorrectPlacementIUSonClick
   1 procedure: cbCorrectPlacementIUCDonClick
   1 procedure: cbClinicalHistoryOnChange
   1 procedure: cbClinicalHistoryChange
   1 procedure: cbCervixSutureYesOnClick
   1 procedure: cbCervixSutureOnClick
   1 procedure: cbCervixPresentYesOnClick
   1 procedure: cbCervixPresentNoOnClick
   1 procedure: cbCervicalPolypOnClick
   1 procedure: cbBladderNormalClick
   1 procedure: cbBladderAbnormalClick
   1 procedure: cbAntiFlexedClick
   1 procedure: cbAdenomyosisPresentOnClick
   1 procedure: cbAdenomyosisNotPresentOnClick
   1 procedure: btnGeneratePercentiles2OnClick
   1 procedure: btnGeneratePercentiles1OnClick
   1 procedure: btnCalGrowthPer2OnClick
   1 procedure: ActiveAdenomyosisControls
   1 function: getPresentationDetail2
   1 function: getPresentationDetail1
   1 function: getPresentationDetail
   1 function: getPregnancyRedated
   1 function: getPregnancyComplication
   1 function: getPlacentalWarning
   1 function: getPlacentalChecks
   1 function: getPlacentaString
   1 function: getPlacenta2Beyond
   1 function: getPlacenta1Position
   1 function: getPlacenta1Beyond
   1 function: getPerigestationalHaemorrhage
   1 function: getPEObstetricHistory
   1 function: getOvaryConclusion
   1 function: getNipsGenderResult
   1 function: getNIPSWarning
   1 function: getNIPSString
   1 function: getNIPSConclusion
   1 function: getMissedMiscarriageFinding
   1 function: getMissedMiscarriageConclusion
   1 function: getMedicalHistory
   1 function: getMCAPSV2
   1 function: getMCAPSV1
   1 function: getLowLyingPlacentaString
   1 function: getLMPString
   1 function: getHeartRateLabel
   1 function: getGenderStr
   1 function: getGender
   1 function: getFollicleString
   1 function: getFirstName
   1 function: getFindingsWarning
   1 function: getFibroidConclusion
   1 function: getFibroidConc
   1 function: getFetalHeartRate
   1 function: getEndometriumType
   1 function: getEndometrialLesion
   1 function: getDuctusVenosus2
   1 function: getDuctusVenosus1
   1 function: getDuctusVenosus
   1 function: getCordInsertionWarning
   1 function: getConclusion
   1 function: getCRL
   1 function: getBioPhysicalMeasurements
   1 function: getBioChemistry
   1 function: getBPD
   1 function: getAssessPlacentalSite
   1 function: getAnatomyNormalViews
   1 function: getAnatomyConclusion
   1 function: getAnatomyConc
   1 function: getAbnormalConclusion
   1 function: RemoveFullStop
   1 function: PrefixZeroDecimal
   1 function: IsLivePregnancy
   1 function: IsAdnexalNormal
   1 function: GetUterusType
   1 function: GetUterusMeasurement
   1 function: GetUterusConclusion
   1 function: GetUterusAppearance
   1 function: GetSuccenturiateType
   1 function: GetSingularAdnexalCystsStr
   1 function: GetSeptumLengthString
   1 function: GetRightOvaryIOTAVascularity
   1 function: GetRightOvaryIOTASolidElements
   1 function: GetRightOvaryIOTAInternalContents
   1 function: GetRightOvaryIOTACystWall
   1 function: GetRightOvaryIOTAAscites
   1 function: GetRightOvaryIOTAAppearance
   1 function: GetRightOvaryCyst
   1 function: GetRightOvaryAppearance
   1 function: GetRightOvary
   1 function: GetRightFollicleCount
   1 function: GetReferalIndications
   1 function: GetProcedureConc
   1 function: GetPolpConc
   1 function: GetPluralCystName
   1 function: GetPlacentalSite
   1 function: GetPlacenta2Measure
   1 function: GetPlacenta2InvertPosition
   1 function: GetPlacenta2
   1 function: GetPlacenta1
   1 function: GetOvaryOverview
   1 function: GetOvaryIOTAClassification
   1 function: GetOvaryConc
   1 function: GetOvarianCystMeasurement
   1 function: GetOvarianCyst
   1 function: GetNeitherOvaryIdentifiedString
   1 function: GetNasalBone
   1 function: GetMultipleEndometrialPolypString
   1 function: GetMultipleEndometrialPolyp
   1 function: GetMultiCystDescriptions
   1 function: GetMenses
   1 function: GetMedication
   1 function: GetLiveFindings
   1 function: GetLiveConclusion
   1 function: GetLeftOvaryIOTAVascularity
   1 function: GetLeftOvaryIOTASolidElements
   1 function: GetLeftOvaryIOTAInternalContents
   1 function: GetLeftOvaryIOTACystWall
   1 function: GetLeftOvaryIOTAAscites
   1 function: GetLeftOvaryIOTAAppearance
   1 function: GetLeftOvaryAppearance
   1 function: GetLeftOvary
   1 function: GetLeftFollicleCount
   1 function: GetLargerMyometrium
   1 function: GetLMPWeeks
   1 function: GetLMPDays
   1 function: GetKidneyAppearance
   1 function: GetIncVasAndVenBlind
   1 function: GetIUCDPlacement
   1 function: GetIOTACystMeasure
   1 function: GetIOTAConc
   1 function: GetHysterectomyString
   1 function: GetHasDistortion
   1 function: GetGynaecologicalSurgery
   1 function: GetGynaecologicalHistory
   1 function: GetGetBulkyUterus
   1 function: GetGestationDetails
   1 function: GetFindings
   1 function: GetFibroidAllClear
   1 function: GetFeatures
   1 function: GetEndometriumSize
   1 function: GetEndometriumConc
   1 function: GetEndometrialPolyp
   1 function: GetEndCycleDays
   1 function: GetEbmHeartMotion
   1 function: GetDualAdnexalCystString
   1 function: GetCystsDimensionsForCystList
   1 function: GetCystsDimensions
   1 function: GetConclusion
   1 function: GetCervixAppearance
   1 function: GetCervicalPolypConc
   1 function: GetCervicalPolyp
   1 function: GetCavProjectionCount
   1 function: GetBothorAll
   1 function: GetAntralNumberString
   1 function: GetAneuploidyRisk
   1 function: GetAdnexalDesc
   1 function: GetAdnexalCystString
   1 function: GetAdnexalConc
   1 function: AddComma
